In [28]:
### rename for unrelaxed
import pandas as pd
import os
# complex names
csv_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/newBM_33.csv"
df = pd.read_csv(csv_path)

complex_list=df["pdb_wchains"].to_list()
for complex_name in complex_list:
    folder_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/"+str(complex_name)+"_esm/"
    prefix = str(complex_name)+"_esm_"  # prefix from af2

    for filename in os.listdir(folder_path):
        if filename.endswith(".pdb"):  # 
            old_path = os.path.join(folder_path, filename)
            new_filename = prefix + filename 
            new_path = os.path.join(folder_path, new_filename)
            
            os.rename(old_path, new_path)  
            print(f"Renamed: {filename} → {new_filename}")
    
    print("renaming complete")

Renamed: ptm0.398_r3_default.pdb → 7r58_H_L_A_esm_ptm0.398_r3_default.pdb
renaming complete
Renamed: ptm0.422_r3_default.pdb → 7sjs_H_L_A_esm_ptm0.422_r3_default.pdb
renaming complete
Renamed: ptm0.570_r3_default.pdb → 7so5_H_L_A_esm_ptm0.570_r3_default.pdb
renaming complete
Renamed: ptm0.483_r3_default.pdb → 7tp4_H_L_A_esm_ptm0.483_r3_default.pdb
renaming complete
Renamed: ptm0.420_r3_default.pdb → 7u2d_H_L_A_esm_ptm0.420_r3_default.pdb
renaming complete
Renamed: ptm0.578_r3_default.pdb → 7u5b_H_L_A_esm_ptm0.578_r3_default.pdb
renaming complete
Renamed: ptm0.522_r3_default.pdb → 7uvf_H_L_A_esm_ptm0.522_r3_default.pdb
renaming complete
Renamed: ptm0.272_r3_default.pdb → 7uz7_H_L_A_esm_ptm0.272_r3_default.pdb
renaming complete
Renamed: ptm0.278_r3_default.pdb → 7uz8_H_L_A_esm_ptm0.278_r3_default.pdb
renaming complete
Renamed: ptm0.413_r3_default.pdb → 7vaz_H_L_A_esm_ptm0.413_r3_default.pdb
renaming complete
Renamed: ptm0.272_r3_default.pdb → 7woa_H_L_A_esm_ptm0.272_r3_default.pdb
renaming complete
Renamed: ptm0.501_r3_default.pdb → 7wrl_H_L_A_esm_ptm0.501_r3_default.pdb
renaming complete
Renamed: ptm0.501_r3_default.pdb → 7wsc_H_L_A_esm_ptm0.501_r3_default.pdb
renaming complete
Renamed: ptm0.604_r3_default.pdb → 7yru_H_L_A_esm_ptm0.604_r3_default.pdb
renaming complete
Renamed: ptm0.486_r3_default.pdb → 7zwi_H_L_A_esm_ptm0.486_r3_default.pdb
renaming complete
Renamed: ptm0.421_r3_default.pdb → 8ath_H_L_A_esm_ptm0.421_r3_default.pdb
renaming complete
Renamed: ptm0.419_r3_default.pdb → 8c3v_H_L_A_esm_ptm0.419_r3_default.pdb
renaming complete
Renamed: ptm0.485_r3_default.pdb → 8cii_H_L_A_esm_ptm0.485_r3_default.pdb
renaming complete
Renamed: ptm0.597_r3_default.pdb → 8d36_H_L_A_esm_ptm0.597_r3_default.pdb
renaming complete
Renamed: ptm0.641_r3_default.pdb → 8d9y_H_L_A_esm_ptm0.641_r3_default.pdb
renaming complete
Renamed: ptm0.430_r3_default.pdb → 8ds5_H_L_A_esm_ptm0.430_r3_default.pdb
renaming complete
Renamed: ptm0.444_r3_default.pdb → 8dxt_H_L_A_esm_ptm0.444_r3_default.pdb
renaming complete
Renamed: ptm0.567_r3_default.pdb → 8f6l_H_L_A_esm_ptm0.567_r3_default.pdb
renaming complete
Renamed: ptm0.464_r3_default.pdb → 8fgx_H_L_A_esm_ptm0.464_r3_default.pdb
renaming complete
Renamed: ptm0.678_r3_default.pdb → 8g2m_H_L_A_esm_ptm0.678_r3_default.pdb
renaming complete
Renamed: ptm0.480_r3_default.pdb → 8g3p_H_L_A_esm_ptm0.480_r3_default.pdb
renaming complete
Renamed: ptm0.512_r3_default.pdb → 8g4p_H_L_A_esm_ptm0.512_r3_default.pdb
renaming complete
Renamed: ptm0.282_r3_default.pdb → 8hc3_H_L_A_esm_ptm0.282_r3_default.pdb
renaming complete
Renamed: ptm0.275_r3_default.pdb → 8hc4_H_L_A_esm_ptm0.275_r3_default.pdb
renaming complete
Renamed: ptm0.317_r3_default.pdb → 8i5h_H_L_A_esm_ptm0.317_r3_default.pdb
renaming complete
Renamed: ptm0.432_r3_default.pdb → 8sdg_H_L_A_esm_ptm0.432_r3_default.pdb
renaming complete
Renamed: ptm0.355_r3_default.pdb → 8tbq_H_L_A_esm_ptm0.355_r3_default.pdb
renaming complete
Renamed: ptm0.499_r3_default.pdb → 7nxx_H_A_esm_ptm0.499_r3_default.pdb
renaming complete
Renamed: ptm0.726_r3_default.pdb → 7q4q_H_L_A_esm_ptm0.726_r3_default.pdb
renaming complete
Renamed: ptm0.417_r3_default.pdb → 7q6c_H_A_esm_ptm0.417_r3_default.pdb
renaming complete
Renamed: ptm0.514_r3_default.pdb → 7q6c_H_L_A_esm_ptm0.514_r3_default.pdb
renaming complete
Renamed: ptm0.407_r3_default.pdb → 7qnw_H_L_A_esm_ptm0.407_r3_default.pdb
renaming complete
Renamed: ptm0.669_r3_default.pdb → 7sp8_H_A_esm_ptm0.669_r3_default.pdb
renaming complete
Renamed: ptm0.515_r3_default.pdb → 7sqp_H_B_esm_ptm0.515_r3_default.pdb
renaming complete
Renamed: ptm0.513_r3_default.pdb → 7sqp_H_A_esm_ptm0.513_r3_default.pdb
renaming complete
Renamed: ptm0.538_r3_default.pdb → 7srk_H_A_esm_ptm0.538_r3_default.pdb
renaming complete
Renamed: ptm0.421_r3_default.pdb → 7sww_H_L_A_esm_ptm0.421_r3_default.pdb
renaming complete
Renamed: ptm0.483_r3_default.pdb → 7t01_H_L_A_esm_ptm0.483_r3_default.pdb
renaming complete
Renamed: ptm0.355_r3_default.pdb → 7t17_H_L_A_esm_ptm0.355_r3_default.pdb
renaming complete
Renamed: ptm0.392_r3_default.pdb → 7t7b_H_L_A_esm_ptm0.392_r3_default.pdb
renaming complete
Renamed: ptm0.721_r3_default.pdb → 7tcq_H_L_A_esm_ptm0.721_r3_default.pdb
renaming complete
Renamed: ptm0.385_r3_default.pdb → 7tl0_H_L_A_esm_ptm0.385_r3_default.pdb
renaming complete
Renamed: ptm0.739_r3_default.pdb → 7tow_H_L_A_esm_ptm0.739_r3_default.pdb
renaming complete
Renamed: ptm0.470_r3_default.pdb → 7tp3_H_L_A_esm_ptm0.470_r3_default.pdb
renaming complete
Renamed: ptm0.217_r3_default.pdb → 7tpr_H_A_esm_ptm0.217_r3_default.pdb
renaming complete
Renamed: ptm0.219_r3_default.pdb → 7tpr_H_B_esm_ptm0.219_r3_default.pdb
renaming complete
Renamed: ptm0.762_r3_default.pdb → 7u0a_H_L_A_esm_ptm0.762_r3_default.pdb
renaming complete
Renamed: ptm0.550_r3_default.pdb → 7uia_H_A_esm_ptm0.550_r3_default.pdb
renaming complete
Renamed: ptm0.549_r3_default.pdb → 7unb_H_L_A_esm_ptm0.549_r3_default.pdb
renaming complete
Renamed: ptm0.327_r3_default.pdb → 7unz_H_A_esm_ptm0.327_r3_default.pdb
renaming complete
Renamed: ptm0.410_r3_default.pdb → 7upb_H_L_A_esm_ptm0.410_r3_default.pdb
renaming complete
Renamed: ptm0.434_r3_default.pdb → 7upk_H_L_A_esm_ptm0.434_r3_default.pdb
renaming complete
Renamed: ptm0.424_r3_default.pdb → 7usv_H_A_esm_ptm0.424_r3_default.pdb
renaming complete
Renamed: ptm0.517_r3_default.pdb → 7uvh_H_L_A_esm_ptm0.517_r3_default.pdb
renaming complete
Renamed: ptm0.465_r3_default.pdb → 7uzc_H_L_A_esm_ptm0.465_r3_default.pdb
renaming complete
Renamed: ptm0.595_r3_default.pdb → 7vke_H_A_esm_ptm0.595_r3_default.pdb
renaming complete
Renamed: ptm0.375_r3_default.pdb → 7voa_H_A_esm_ptm0.375_r3_default.pdb
renaming complete
Renamed: ptm0.287_r3_default.pdb → 7wbh_H_L_A_esm_ptm0.287_r3_default.pdb
renaming complete
Renamed: ptm0.285_r3_default.pdb → 7wcp_H_L_A_esm_ptm0.285_r3_default.pdb
renaming complete
Renamed: ptm0.428_r3_default.pdb → 7wg3_H_L_A_esm_ptm0.428_r3_default.pdb
renaming complete
Renamed: ptm0.482_r3_default.pdb → 7wn0_H_A_esm_ptm0.482_r3_default.pdb
renaming complete
Renamed: ptm0.489_r3_default.pdb → 7wn1_H_A_esm_ptm0.489_r3_default.pdb
renaming complete
Renamed: ptm0.497_r3_default.pdb → 7wog_H_L_A_esm_ptm0.497_r3_default.pdb
renaming complete
Renamed: ptm0.286_r3_default.pdb → 7wpe_H_L_A_esm_ptm0.286_r3_default.pdb
renaming complete
Renamed: ptm0.307_r3_default.pdb → 7wro_H_L_A_esm_ptm0.307_r3_default.pdb
renaming complete
Renamed: ptm0.277_r3_default.pdb → 7wtf_H_L_A_esm_ptm0.277_r3_default.pdb
renaming complete
Renamed: ptm0.481_r3_default.pdb → 7wtg_H_L_A_esm_ptm0.481_r3_default.pdb
renaming complete
Renamed: ptm0.277_r3_default.pdb → 7wti_H_L_A_esm_ptm0.277_r3_default.pdb
renaming complete
Renamed: ptm0.380_r3_default.pdb → 7x2j_H_A_esm_ptm0.380_r3_default.pdb
renaming complete
Renamed: ptm0.360_r3_default.pdb → 7x2l_H_A_esm_ptm0.360_r3_default.pdb
renaming complete
Renamed: ptm0.389_r3_default.pdb → 7x2m_H_A_esm_ptm0.389_r3_default.pdb
renaming complete
Renamed: ptm0.280_r3_default.pdb → 7x6a_H_L_A_esm_ptm0.280_r3_default.pdb
renaming complete
Renamed: ptm0.390_r3_default.pdb → 7x7e_H_A_esm_ptm0.390_r3_default.pdb
renaming complete
Renamed: ptm0.489_r3_default.pdb → 7x7t_H_L_A_esm_ptm0.489_r3_default.pdb
renaming complete
Renamed: ptm0.576_r3_default.pdb → 7x8p_H_L_A_esm_ptm0.576_r3_default.pdb
renaming complete
Renamed: ptm0.479_r3_default.pdb → 7xcz_H_L_A_esm_ptm0.479_r3_default.pdb
renaming complete
Renamed: ptm0.285_r3_default.pdb → 7xdb_H_L_A_esm_ptm0.285_r3_default.pdb
renaming complete
Renamed: ptm0.488_r3_default.pdb → 7xy8_H_L_A_esm_ptm0.488_r3_default.pdb
renaming complete
Renamed: ptm0.576_r3_default.pdb → 7yds_H_L_A_esm_ptm0.576_r3_default.pdb
renaming complete
Renamed: ptm0.548_r3_default.pdb → 7yiz_H_L_A_esm_ptm0.548_r3_default.pdb
renaming complete
Renamed: ptm0.386_r3_default.pdb → 7z1c_H_A_esm_ptm0.386_r3_default.pdb
renaming complete
Renamed: ptm0.465_r3_default.pdb → 7z1x_H_A_esm_ptm0.465_r3_default.pdb
renaming complete
Renamed: ptm0.606_r3_default.pdb → 7z2m_H_L_A_esm_ptm0.606_r3_default.pdb
renaming complete
Renamed: ptm0.622_r3_default.pdb → 7zk1_H_A_esm_ptm0.622_r3_default.pdb
renaming complete
Renamed: ptm0.637_r3_default.pdb → 7zk1_H_B_esm_ptm0.637_r3_default.pdb
renaming complete
Renamed: ptm0.578_r3_default.pdb → 7zkz_H_A_esm_ptm0.578_r3_default.pdb
renaming complete
Renamed: ptm0.371_r3_default.pdb → 7zlk_H_L_A_esm_ptm0.371_r3_default.pdb
renaming complete
Renamed: ptm0.598_r3_default.pdb → 7zml_H_A_esm_ptm0.598_r3_default.pdb
renaming complete
Renamed: ptm0.603_r3_default.pdb → 7zmm_H_A_esm_ptm0.603_r3_default.pdb
renaming complete
Renamed: ptm0.571_r3_default.pdb → 7zw1_H_A_esm_ptm0.571_r3_default.pdb
renaming complete
Renamed: ptm0.367_r3_default.pdb → 7zxu_H_A_esm_ptm0.367_r3_default.pdb
renaming complete
Renamed: ptm0.371_r3_default.pdb → 7zxu_H_B_esm_ptm0.371_r3_default.pdb
renaming complete
Renamed: ptm0.683_r3_default.pdb → 8b17_H_A_esm_ptm0.683_r3_default.pdb
renaming complete
Renamed: ptm0.683_r3_default.pdb → 8b8i_H_A_esm_ptm0.683_r3_default.pdb
renaming complete
Renamed: ptm0.669_r3_default.pdb → 8be2_H_A_esm_ptm0.669_r3_default.pdb
renaming complete
Renamed: ptm0.542_r3_default.pdb → 8c3l_H_A_esm_ptm0.542_r3_default.pdb
renaming complete
Renamed: ptm0.546_r3_default.pdb → 8ce4_H_A_esm_ptm0.546_r3_default.pdb
renaming complete
Renamed: ptm0.633_r3_default.pdb → 8che_H_L_A_esm_ptm0.633_r3_default.pdb
renaming complete
Renamed: ptm0.280_r3_default.pdb → 8cin_H_L_A_esm_ptm0.280_r3_default.pdb
renaming complete
Renamed: ptm0.217_r3_default.pdb → 8cxn_H_A_esm_ptm0.217_r3_default.pdb
renaming complete
Renamed: ptm0.216_r3_default.pdb → 8cxq_H_A_esm_ptm0.216_r3_default.pdb
renaming complete
Renamed: ptm0.213_r3_default.pdb → 8cy6_H_A_esm_ptm0.213_r3_default.pdb
renaming complete
Renamed: ptm0.214_r3_default.pdb → 8cy9_H_A_esm_ptm0.214_r3_default.pdb
renaming complete
Renamed: ptm0.218_r3_default.pdb → 8cyb_H_A_esm_ptm0.218_r3_default.pdb
renaming complete
Renamed: ptm0.219_r3_default.pdb → 8cyc_H_A_esm_ptm0.219_r3_default.pdb
renaming complete
Renamed: ptm0.212_r3_default.pdb → 8cyd_H_A_esm_ptm0.212_r3_default.pdb
renaming complete
Renamed: ptm0.376_r3_default.pdb → 8cyj_H_B_esm_ptm0.376_r3_default.pdb
renaming complete
Renamed: ptm0.394_r3_default.pdb → 8cyj_H_A_esm_ptm0.394_r3_default.pdb
renaming complete
Renamed: ptm0.391_r3_default.pdb → 8cyj_H_C_esm_ptm0.391_r3_default.pdb
renaming complete
Renamed: ptm0.387_r3_default.pdb → 8cyj_H_D_esm_ptm0.387_r3_default.pdb
renaming complete
Renamed: ptm0.405_r3_default.pdb → 8cz5_H_L_A_esm_ptm0.405_r3_default.pdb
renaming complete
Renamed: ptm0.748_r3_default.pdb → 8d47_H_L_A_esm_ptm0.748_r3_default.pdb
renaming complete
Renamed: ptm0.650_r3_default.pdb → 8d9z_H_L_A_esm_ptm0.650_r3_default.pdb
renaming complete
Renamed: ptm0.748_r3_default.pdb → 8da0_H_L_A_esm_ptm0.748_r3_default.pdb
renaming complete
Renamed: ptm0.641_r3_default.pdb → 8da1_H_L_A_esm_ptm0.641_r3_default.pdb
renaming complete
Renamed: ptm0.464_r3_default.pdb → 8dad_H_L_A_esm_ptm0.464_r3_default.pdb
renaming complete
Renamed: ptm0.392_r3_default.pdb → 8dg9_H_L_A_esm_ptm0.392_r3_default.pdb
renaming complete
Renamed: ptm0.748_r3_default.pdb → 8dgu_H_L_A_esm_ptm0.748_r3_default.pdb
renaming complete
Renamed: ptm0.377_r3_default.pdb → 8dly_H_A_esm_ptm0.377_r3_default.pdb
renaming complete
Renamed: ptm0.553_r3_default.pdb → 8dqu_H_A_esm_ptm0.553_r3_default.pdb
renaming complete
Renamed: ptm0.504_r3_default.pdb → 8dxu_H_L_A_esm_ptm0.504_r3_default.pdb
renaming complete
Renamed: ptm0.622_r3_default.pdb → 8e0e_H_A_esm_ptm0.622_r3_default.pdb
renaming complete
Renamed: ptm0.497_r3_default.pdb → 8e6j_H_L_A_esm_ptm0.497_r3_default.pdb
renaming complete
Renamed: ptm0.667_r3_default.pdb → 8eln_H_A_esm_ptm0.667_r3_default.pdb
renaming complete
Renamed: ptm0.316_r3_default.pdb → 8emz_H_A_esm_ptm0.316_r3_default.pdb
renaming complete
Renamed: ptm0.316_r3_default.pdb → 8en3_H_A_esm_ptm0.316_r3_default.pdb
renaming complete
Renamed: ptm0.475_r3_default.pdb → 8ez3_H_L_A_esm_ptm0.475_r3_default.pdb
renaming complete
Renamed: ptm0.591_r3_default.pdb → 8f6o_H_L_A_esm_ptm0.591_r3_default.pdb
renaming complete
Renamed: ptm0.742_r3_default.pdb → 8f95_H_L_A_esm_ptm0.742_r3_default.pdb
renaming complete
Renamed: ptm0.736_r3_default.pdb → 8f9f_H_L_A_esm_ptm0.736_r3_default.pdb
renaming complete
Renamed: ptm0.748_r3_default.pdb → 8f9s_H_L_A_esm_ptm0.748_r3_default.pdb
renaming complete
Renamed: ptm0.748_r3_default.pdb → 8f9t_H_L_A_esm_ptm0.748_r3_default.pdb
renaming complete
Renamed: ptm0.744_r3_default.pdb → 8fa6_H_L_A_esm_ptm0.744_r3_default.pdb
renaming complete
Renamed: ptm0.433_r3_default.pdb → 8fas_H_L_A_esm_ptm0.433_r3_default.pdb
renaming complete
Renamed: ptm0.737_r3_default.pdb → 8fb6_H_L_A_esm_ptm0.737_r3_default.pdb
renaming complete
Renamed: ptm0.727_r3_default.pdb → 8fb7_H_L_A_esm_ptm0.727_r3_default.pdb
renaming complete
Renamed: ptm0.688_r3_default.pdb → 8fbw_H_L_A_esm_ptm0.688_r3_default.pdb
renaming complete
Renamed: ptm0.211_r3_default.pdb → 8g74_H_A_esm_ptm0.211_r3_default.pdb
renaming complete
Renamed: ptm0.512_r3_default.pdb → 8gb6_H_L_A_esm_ptm0.512_r3_default.pdb
renaming complete
Renamed: ptm0.745_r3_default.pdb → 8gho_H_L_A_esm_ptm0.745_r3_default.pdb
renaming complete
Renamed: ptm0.574_r3_default.pdb → 8gni_H_A_esm_ptm0.574_r3_default.pdb
renaming complete
Renamed: ptm0.482_r3_default.pdb → 8gzz_H_L_A_esm_ptm0.482_r3_default.pdb
renaming complete
Renamed: ptm0.395_r3_default.pdb → 8h3x_H_A_esm_ptm0.395_r3_default.pdb
renaming complete
Renamed: ptm0.424_r3_default.pdb → 8h3y_H_A_esm_ptm0.424_r3_default.pdb
renaming complete
Renamed: ptm0.374_r3_default.pdb → 8h5u_H_A_esm_ptm0.374_r3_default.pdb
renaming complete
Renamed: ptm0.282_r3_default.pdb → 8heb_H_L_A_esm_ptm0.282_r3_default.pdb
renaming complete
Renamed: ptm0.285_r3_default.pdb → 8hp9_H_L_A_esm_ptm0.285_r3_default.pdb
renaming complete
Renamed: ptm0.285_r3_default.pdb → 8hp9_H_L_B_esm_ptm0.285_r3_default.pdb
renaming complete
Renamed: ptm0.286_r3_default.pdb → 8hpv_H_L_A_esm_ptm0.286_r3_default.pdb
renaming complete
Renamed: ptm0.604_r3_default.pdb → 8hxq_H_A_esm_ptm0.604_r3_default.pdb
renaming complete
Renamed: ptm0.378_r3_default.pdb → 8ido_H_A_esm_ptm0.378_r3_default.pdb
renaming complete
Renamed: ptm0.481_r3_default.pdb → 8il3_H_L_A_esm_ptm0.481_r3_default.pdb
renaming complete
Renamed: ptm0.457_r3_default.pdb → 8j7t_H_L_A_esm_ptm0.457_r3_default.pdb
renaming complete
Renamed: ptm0.674_r3_default.pdb → 8ont_H_A_esm_ptm0.674_r3_default.pdb
renaming complete
Renamed: ptm0.325_r3_default.pdb → 8opr_H_B_esm_ptm0.325_r3_default.pdb
renaming complete
Renamed: ptm0.333_r3_default.pdb → 8opr_H_A_esm_ptm0.333_r3_default.pdb
renaming complete
Renamed: ptm0.623_r3_default.pdb → 8oud_H_A_esm_ptm0.623_r3_default.pdb
renaming complete
Renamed: ptm0.532_r3_default.pdb → 8oxw_H_L_A_esm_ptm0.532_r3_default.pdb
renaming complete
Renamed: ptm0.632_r3_default.pdb → 8oxx_H_L_A_esm_ptm0.632_r3_default.pdb
renaming complete
Renamed: ptm0.584_r3_default.pdb → 8oxy_H_L_A_esm_ptm0.584_r3_default.pdb
renaming complete
Renamed: ptm0.611_r3_default.pdb → 8pyr_H_A_esm_ptm0.611_r3_default.pdb
renaming complete
Renamed: ptm0.529_r3_default.pdb → 8qf5_H_A_esm_ptm0.529_r3_default.pdb
renaming complete
Renamed: ptm0.491_r3_default.pdb → 8qrg_H_L_A_esm_ptm0.491_r3_default.pdb
renaming complete
Renamed: ptm0.283_r3_default.pdb → 8r1d_H_L_A_esm_ptm0.283_r3_default.pdb
renaming complete
Renamed: ptm0.374_r3_default.pdb → 8sgn_H_L_A_esm_ptm0.374_r3_default.pdb
renaming complete
Renamed: ptm0.378_r3_default.pdb → 8sk5_H_A_esm_ptm0.378_r3_default.pdb
renaming complete
Renamed: ptm0.359_r3_default.pdb → 7e53_B_A_esm_ptm0.359_r3_default.pdb
renaming complete
Renamed: ptm0.437_r3_default.pdb → 7e72_C_D_F_esm_ptm0.437_r3_default.pdb
renaming complete
Renamed: ptm0.572_r3_default.pdb → 7anq_B_A_esm_ptm0.572_r3_default.pdb
renaming complete
Renamed: ptm0.635_r3_default.pdb → 7aqy_C_B_esm_ptm0.635_r3_default.pdb
renaming complete
Renamed: ptm0.631_r3_default.pdb → 7ar0_B_A_esm_ptm0.631_r3_default.pdb
renaming complete
Renamed: ptm0.548_r3_default.pdb → 7bbj_H_L_A_esm_ptm0.548_r3_default.pdb
renaming complete
Renamed: ptm0.386_r3_default.pdb → 7bnv_H_L_A_esm_ptm0.386_r3_default.pdb
renaming complete
Renamed: ptm0.593_r3_default.pdb → 7daa_H_L_A_esm_ptm0.593_r3_default.pdb
renaming complete
Renamed: ptm0.528_r3_default.pdb → 7l6v_B_A_esm_ptm0.528_r3_default.pdb
renaming complete
Renamed: ptm0.507_r3_default.pdb → 7l6v_C_A_esm_ptm0.507_r3_default.pdb
renaming complete
Renamed: ptm0.555_r3_default.pdb → 7l6v_D_A_esm_ptm0.555_r3_default.pdb
renaming complete
Renamed: ptm0.543_r3_default.pdb → 7l6v_F_A_esm_ptm0.543_r3_default.pdb
renaming complete
Renamed: ptm0.340_r3_default.pdb → 7l7r_B_A_G_esm_ptm0.340_r3_default.pdb
renaming complete
Renamed: ptm0.384_r3_default.pdb → 7l7r_D_C_G_esm_ptm0.384_r3_default.pdb
renaming complete
Renamed: ptm0.561_r3_default.pdb → 7lr4_H_L_D_esm_ptm0.561_r3_default.pdb
renaming complete
Renamed: ptm0.533_r3_default.pdb → 7lzp_E_D_esm_ptm0.533_r3_default.pdb
renaming complete
Renamed: ptm0.538_r3_default.pdb → 7m1h_E_A_esm_ptm0.538_r3_default.pdb
renaming complete
Renamed: ptm0.534_r3_default.pdb → 7m1h_F_A_esm_ptm0.534_r3_default.pdb
renaming complete
Renamed: ptm0.558_r3_default.pdb → 7m1h_G_A_esm_ptm0.558_r3_default.pdb
renaming complete
Renamed: ptm0.482_r3_default.pdb → 7mzj_H_L_A_esm_ptm0.482_r3_default.pdb
renaming complete
Renamed: ptm0.292_r3_default.pdb → 7mzk_N_M_B_esm_ptm0.292_r3_default.pdb
renaming complete
Renamed: ptm0.435_r3_default.pdb → 7mzm_H_L_A_esm_ptm0.435_r3_default.pdb
renaming complete
Renamed: ptm0.417_r3_default.pdb → 7n4j_H_L_A_esm_ptm0.417_r3_default.pdb
renaming complete
Renamed: ptm0.498_r3_default.pdb → 7na9_D_A_esm_ptm0.498_r3_default.pdb
renaming complete
Renamed: ptm0.313_r3_default.pdb → 7nfq_C_A_esm_ptm0.313_r3_default.pdb
renaming complete
Renamed: ptm0.317_r3_default.pdb → 7nfr_B_A_esm_ptm0.317_r3_default.pdb
renaming complete
Renamed: ptm0.664_r3_default.pdb → 7nx0_D_C_esm_ptm0.664_r3_default.pdb
renaming complete
Renamed: ptm0.531_r3_default.pdb → 7nx3_B_C_F_esm_ptm0.531_r3_default.pdb
renaming complete
Renamed: ptm0.510_r3_default.pdb → 7ps0_H_L_E_esm_ptm0.510_r3_default.pdb
renaming complete
Renamed: ptm0.489_r3_default.pdb → 7ps2_H_L_G_esm_ptm0.489_r3_default.pdb
renaming complete
Renamed: ptm0.507_r3_default.pdb → 7ps4_H_L_E_esm_ptm0.507_r3_default.pdb
renaming complete
Renamed: ptm0.460_r3_default.pdb → 7ps6_H_L_E_esm_ptm0.460_r3_default.pdb
renaming complete
Renamed: ptm0.438_r3_default.pdb → 7q0g_A_B_E_esm_ptm0.438_r3_default.pdb
renaming complete
Renamed: ptm0.406_r3_default.pdb → 7q0i_H_L_A_esm_ptm0.406_r3_default.pdb
renaming complete
Renamed: ptm0.473_r3_default.pdb → 7s11_I_M_D_esm_ptm0.473_r3_default.pdb
renaming complete
Renamed: ptm0.517_r3_default.pdb → 7t5f_C_A_esm_ptm0.517_r3_default.pdb
renaming complete
Renamed: ptm0.558_r3_default.pdb → 7t5f_E_D_esm_ptm0.558_r3_default.pdb
renaming complete
Renamed: ptm0.350_r3_default.pdb → 7vnb_A_B_esm_ptm0.350_r3_default.pdb
renaming complete
Renamed: ptm0.526_r3_default.pdb → 7vux_H_L_A_esm_ptm0.526_r3_default.pdb
renaming complete

In [35]:
## dockq Functions

import os
import sys
import csv
import glob

from DockQ.DockQ import load_PDB, run_on_all_native_interfaces
from statistics import mean

def merge_chains(model, chains_to_merge):
    print(f"Merging chains {chains_to_merge} in model")
    for chain in chains_to_merge[1:]:
        for res in list(model[chain]):
            res.id = (chains_to_merge[0], res.id[1], res.id[2])
            model[chains_to_merge[0]].add(res)
        model.detach_child(chain)
    model[chains_to_merge[0]].id = "".join(chains_to_merge)
    return model

def calculate_dockq(model, native, chain_map):
    print(f"Calculating DockQ score with chain_map: {chain_map}")
    results, dockq_score = run_on_all_native_interfaces(model, native, chain_map=chain_map)
    return results, dockq_score

def process_models(models):
    results_list = []
    for model_file, native_file in models:
        print(f"Processing model: {model_file}, native: {native_file}")
        model_id = os.path.basename(model_file).split(".")[0]
        model = load_PDB(model_file)
        native = load_PDB(native_file)

        chain_ids = list(model.child_dict.keys())
        print(chain_ids)
        native_chain_ids = list(native.child_dict.keys())

        if len(chain_ids) == 3:
            print(f"Model {model_id} has 3 chains: {chain_ids}")
            
            # Merge A and B chains and recalculate
            model_merged = merge_chains(model, chain_ids[:2])
            print(model_merged)
            native_merged = merge_chains(native, native_chain_ids[:2])
            chain_map_merged = {native_chain_ids[2]: chain_ids[2], "".join(native_chain_ids[:2]): "".join(chain_ids[:2])}
            results_merged, dockq_score_merged = calculate_dockq(model_merged, native_merged, chain_map_merged)
            merged_result = results_merged[list(results_merged.keys())[0]]
            results_list.append((model_id, merged_result['DockQ'], merged_result['fnat'],
                                merged_result['iRMSD'], merged_result['LRMSD'],merged_result['F1']))

        elif len(chain_ids) == 2:
            print(f"Model {model_id} has 2 chains: {chain_ids}")
            chain_map = {native_chain_ids[0]: chain_ids[0], native_chain_ids[1]: chain_ids[1]}
            results, dockq_score = calculate_dockq(model, native, chain_map)
            results_list.append((model_id, results[list(results.keys())[0]]['DockQ'], results[list(results.keys())[0]]['fnat'],
                                results[list(results.keys())[0]]['iRMSD'], results[list(results.keys())[0]]['LRMSD'],
                                results[list(results.keys())[0]]['F1']))

        else:
            print(f"Model {model_id} does not have 2 or 3 chains: {chain_ids}, skipping.")
            continue

    return results_list

def save_results_to_csv(results, filename):
    print(f"Saving results to CSV file: {filename}")
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['model_id', 'DockQ', 'fnat',"iRMSD","LRMSD","F1"])

        for model_id, dockq, fnat, irms, lrms, f1 in results:
            print(f"Writing row: {model_id}, {dockq}, {fnat}, {irms},{lrms},{f1}")
            writer.writerow([model_id, dockq, fnat, irms, lrms,f1])
    
def main(directory, original_directory):
    pdb_files = glob.glob(f"{directory}/*_esm*.pdb")
    if not pdb_files:
        print(f"No PDB files found in directory: {directory}")
        return

    print(f"Found PDB files: {pdb_files}")
    models = []

    for pdb_file in pdb_files:
        pdb_id_chains = os.path.basename(pdb_file).split('_esm')[0] # for af2.3
        print(f"Searching for original files for: {pdb_id_chains}")
        original_pdb_files = glob.glob(f"{original_directory}/{pdb_id_chains}.pdb")  # Find matching original PDB files
        print(f"Found original PDB files: {original_pdb_files} for {pdb_file}")
        if not original_pdb_files:
            print(f"No matching original PDB file found for {pdb_file}, skipping.")
            continue
        for original_pdb_file in original_pdb_files:
            models.append((pdb_file, original_pdb_file))
            print(f"Adding model-native pair: {pdb_file}, {original_pdb_file}")

    if not models:
        print("No valid model-native pairs found. Exiting.")
        return

    results = process_models(models)
    save_results_to_csv(results, str(pdb_id_chains)+'_'+str(method)+'_dockq_fnat_scores.csv')

In [36]:
#### dockq and fnat calculation running
import pandas as pd
import glob
import os

csv_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/newBM_33.csv"
df = pd.read_csv(csv_path)

complex_list=df["pdb_wchains"].to_list()
preds = ["esm"]
# method = preds[4]
for method in preds:
    os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/"+str(method))
    
    # dockq functions 
    for i in complex_list:
        fpath = f"/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/{method}/{i}_{method}/"
        directory = os.path.expanduser(fpath)
        original_directory = os.path.expanduser("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs")
        main(directory, original_directory)
    
    
    def combine_csv_files(folder_path, output_file=None):
        # Find all CSV files in the folder
        csv_files = glob.glob(os.path.join(folder_path, "*dockq_fnat_scores.csv"))
        
        # Read and combine all CSVs
        df_list = [pd.read_csv(file) for file in csv_files]
        combined_df = pd.concat(df_list, ignore_index=True)
        
        # Save to CSV if an output file is provided
        if output_file:
            combined_df.to_csv(output_file, index=False)
            print(f"Combined CSV saved to {output_file}")
        
        return combined_df
    
    # Example usage
    folder_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/"+str(method)  
    output_csv = str(method)+"_dockq_fnat_scores.csv"  
    combined_df = combine_csv_files(folder_path, output_csv)

Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb']
Searching for original files for: 7r58_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7r58_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7r58_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7r58_H_L_A.pdb
['A', 'B', 'C']
Model 7r58_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7r58_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7r58_H_L_A_esm_ptm0, 0.004079530880826214, 0, 33.30035861207476,83.6755038924622,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb']
Searching for original files for: 7sjs_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7sjs_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7sjs_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7sjs_H_L_A.pdb
['A', 'B', 'C']
Model 7sjs_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7sjs_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7sjs_H_L_A_esm_ptm0, 0.020339818052180558, 0, 31.858191628877137,34.004926844736914,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb']
Searching for original files for: 7so5_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7so5_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7so5_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7so5_H_L_A.pdb
['A', 'B', 'C']
Model 7so5_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7so5_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7so5_H_L_A_esm_ptm0, 0.004851104821623911, 0, 25.214258192325154,80.49855462472793,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb']
Searching for original files for: 7tp4_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7tp4_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7tp4_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7tp4_H_L_A.pdb
['A', 'B', 'C']
Model 7tp4_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7tp4_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7tp4_H_L_A_esm_ptm0, 0.0053265228577451425, 0, 28.44112684187952,73.4769595402507,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb']
Searching for original files for: 7u2d_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u2d_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u2d_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u2d_H_L_A.pdb
['A', 'B', 'C']
Model 7u2d_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7u2d_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7u2d_H_L_A_esm_ptm0, 0.00472583036703187, 0, 25.3359395681336,81.79143153898137,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb']
Searching for original files for: 7u5b_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u5b_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u5b_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7u5b_H_L_A.pdb
['A', 'B', 'C']
Model 7u5b_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7u5b_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7u5b_H_L_A_esm_ptm0, 0.0061348726393173165, 0, 21.970530854450196,71.9483679332199,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb']
Searching for original files for: 7uvf_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uvf_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uvf_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uvf_H_L_A.pdb
['A', 'B', 'C']
Model 7uvf_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7uvf_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7uvf_H_L_A_esm_ptm0, 0.005383980180825241, 0, 23.6703259525998,76.63669503687652,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb']
Searching for original files for: 7uz7_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz7_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz7_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz7_H_L_A.pdb
['A', 'B', 'C']
Model 7uz7_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7uz7_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7uz7_H_L_A_esm_ptm0, 0.004894022144103986, 0, 31.99158169252991,75.58497144855255,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb']
Searching for original files for: 7uz8_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz8_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz8_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7uz8_H_L_A.pdb
['A', 'B', 'C']
Model 7uz8_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7uz8_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7uz8_H_L_A_esm_ptm0, 0.0033999238254210327, 0, 37.476395046594405,91.26117746162518,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb']
Searching for original files for: 7vaz_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7vaz_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7vaz_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7vaz_H_L_A.pdb
['A', 'B', 'C']
Model 7vaz_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7vaz_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7vaz_H_L_A_esm_ptm0, 0.009423977142657023, 0, 29.855456394085746,52.2794138784906,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb']
Searching for original files for: 7woa_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7woa_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7woa_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7woa_H_L_A.pdb
['A', 'B', 'C']
Model 7woa_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7woa_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7woa_H_L_A_esm_ptm0, 0.002182379205003369, 0, 31.320550256125724,129.97232375340707,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb']
Searching for original files for: 7wrl_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wrl_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wrl_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wrl_H_L_A.pdb
['A', 'B', 'C']
Model 7wrl_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7wrl_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7wrl_H_L_A_esm_ptm0, 0.005180938224145235, 0, 26.557529467269113,75.97287247531541,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb']
Searching for original files for: 7wsc_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wsc_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wsc_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7wsc_H_L_A.pdb
['A', 'B', 'C']
Model 7wsc_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7wsc_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7wsc_H_L_A_esm_ptm0, 0.005239190151391658, 0, 26.206010371457992,75.69699208168745,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb']
Searching for original files for: 7yru_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7yru_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7yru_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7yru_H_L_A.pdb
['A', 'B', 'C']
Model 7yru_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7yru_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7yru_H_L_A_esm_ptm0, 0.008228741435884456, 0, 19.193555348759354,61.7161694121326,0.0
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb']
Searching for original files for: 7zwi_H_L_A
Found original PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7zwi_H_L_A.pdb'] for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb
Adding model-native pair: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb, /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7zwi_H_L_A.pdb
Processing model: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb, native: /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/original_pdbs/7zwi_H_L_A.pdb
['A', 'B', 'C']
Model 7zwi_H_L_A_esm_ptm0 has 3 chains: ['A', 'B', 'C']
Merging chains ['A', 'B'] in model
<Model id=/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb>
Merging chains ['A', 'B'] in model
Calculating DockQ score with chain_map: {'C': 'C', 'AB': 'AB'}
Saving results to CSV file: 7zwi_H_L_A_esm_dockq_fnat_scores.csv
Writing row: 7zwi_H_L_A_esm_ptm0, 0.006172954851930818, 0, 22.21602511395229,71.38323425978224,0.0

In [30]:
import json
import numpy as np

import pandas as pd
import glob
import os

csv_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/newBM_33.csv"
df = pd.read_csv(csv_path)

complex_list=df["pdb_wchains"].to_list()

os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm")

for f in complex_list:
    os.chdir(f"/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/{f}_esm")
# File paths
    txt_file = glob.glob("*pae.txt")
    json_file = "converted_pae.json"

    # Read the PAE data from the text file
    pae_data = []
    with open(txt_file[0], "r") as f:
        for line in f:
            values = list(map(float, line.strip().split()))
            pae_data.append(values)
    
    pae_json = {"pae": pae_data}
    
    with open(json_file, "w") as f:
        json.dump(pae_json, f, indent=4)
    
    print(f"Converted JSON saved to: {json_file}")

Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json
Converted JSON saved to: converted_pae.json

In [2]:
#pdockq2 funcs
from Bio.PDB import PDBIO
from Bio.PDB.PDBParser import PDBParser
from Bio.PDB.Selection import unfold_entities

import numpy as np
import sys,os
import argparse
import pickle
import itertools
import pandas as pd
from scipy.optimize import curve_fit

def retrieve_IFplddt(structure, chain1, chain2_lst, max_dist):
    ## generate a dict to save IF_res_id
    chain_lst = list(chain1) + chain2_lst

    ifplddt = []
    contact_chain_lst = []
    for res1 in structure[0][chain1]:
        for chain2 in chain2_lst:
            count = 0
            for res2 in structure[0][chain2]:

                if res1.has_id('CA') and res2.has_id('CA'):
                   dis = abs(res1['CA']-res2['CA'])
                   ## add criteria to filter out disorder res
                   if dis <= max_dist:
                      ifplddt.append(res1['CA'].get_bfactor())
                      count += 1

                elif res1.has_id('CB') and res2.has_id('CB'):
                   dis = abs(res1['CB']-res2['CB'])
                   if dis <= max_dist:
                      ifplddt.append(res1['CB'].get_bfactor())
                      count += 1
            if count > 0:
              contact_chain_lst.append(chain2)
    contact_chain_lst = sorted(list(set(contact_chain_lst)))   

    if len(ifplddt)>0:
       IF_plddt_avg = np.mean(ifplddt)
    else:
       IF_plddt_avg = 0
    # print(IF_plddt_avg)

    return IF_plddt_avg, contact_chain_lst


def retrieve_IFPAEinter(structure, paeMat, contact_lst, max_dist):
    chain_lst = [x.id for x in structure[0]]
    seqlen = [len(x) for x in structure[0]]
    ifch1_col=[]
    ifch2_col=[]
    ch1_lst=[]
    ch2_lst=[]
    ifpae_avg = []
    d=10
    for ch1_idx in range(len(chain_lst)):
      idx = chain_lst.index(chain_lst[ch1_idx])
      ch1_sta=sum(seqlen[:idx])
      ch1_end=ch1_sta+seqlen[idx]
      ifpae_col = []   
      ## for each chain that shares an interface with chain1, retrieve the PAE matrix for the specific part.
      for contact_ch in contact_lst[ch1_idx]:
        index = chain_lst.index(contact_ch)
        ch_sta = sum(seqlen[:index])
        ch_end = ch_sta+seqlen[index]
        paeMat = np.array(paeMat)

        remain_paeMatrix = paeMat[ch1_sta:ch1_end,ch_sta:ch_end]

        mat_x = -1
        for res1 in structure[0][chain_lst[ch1_idx]]:
          mat_x += 1
          mat_y = -1
          for res2 in structure[0][contact_ch]:
              mat_y+=1
              if res1['CA'] - res2['CA'] <=max_dist:
                 ifpae_col.append(remain_paeMatrix[mat_x,mat_y])
      ## normalize by d(10A) first and then get the average
      if not ifpae_col:
        ifpae_avg.append(0)
      else:
        norm_if_interpae=np.mean(1/(1+(np.array(ifpae_col)/d)**2))
        ifpae_avg.append(norm_if_interpae)

    return ifpae_avg

def calc_pmidockq(ifpae_norm, ifplddt):
    df = pd.DataFrame()
    df['ifpae_norm'] = ifpae_norm
    df['ifplddt'] = ifplddt

    df['prot'] = df.ifpae_norm*df.ifplddt
    fitpopt = [1.31034849e+00, 8.47326239e+01, 7.47157696e-02, 5.01886443e-03] ## from orignal pdcokq2 fit  
    df['pmidockq'] = sigmoid(df.prot.values, *fitpopt)
    return df

def sigmoid(x, L ,x0, k, b):
    y = L / (1 + np.exp(-k*(x-x0)))+b
    return (y)

def process_pdb_file(pdb_file, json_file, distance, file_id, chains_part="", pae=None):
    
    # Parse the PDB file
    pdbp = PDBParser(QUIET=True)
    structure = pdbp.get_structure('', pdb_file)
    chains = [chain.id for chain in structure[0]]

    remain_contact_lst = []
    plddt_lst = []

    for idx in range(len(chains)):
        chain2_lst = list(set(chains)-set(chains[idx]))
        IF_plddt, contact_lst = retrieve_IFplddt(structure, chains[idx], chain2_lst, distance)
        plddt_lst.append(IF_plddt)
        remain_contact_lst.append(contact_lst)
    
    avgif_pae = retrieve_IFPAEinter(structure, pae, remain_contact_lst, distance)

    res = calc_pmidockq(avgif_pae, plddt_lst)
    pdb_id = os.path.basename(pdb_file).split('_')[0]
    
    result = {
        "model_id": pdb_file,
        "pdb_id": file_id,
        "Pdb_id_with_chains": '{0}_{1}'.format(pdb_id, chains_part),
        "ifpae_norm_ag": res['ifpae_norm'].tolist()[-1],  #  all values
        "ifpae_norm_avg": np.mean(res['ifpae_norm']),  #  average
        "ifplddt_ag": res['ifplddt'].tolist()[-1],  #  all values
        "ifplddt_avg": np.mean(res['ifplddt']),  #  average
        "PdockQ2 Antigen": res['pmidockq'].tolist()[-1], #original - antigen score
        "PdockQ2_avg": np.mean(res['pmidockq']),  #  average
    }
    return result

In [3]:
import os
import glob
import json
import pandas as pd

def find_matching_json(pdb_file, directory):
   
    json_files = glob.glob(os.path.join(directory, "converted_pae.json"))
    
    print(f"Found JSON files: {json_files}")
    
    return json_files[0] if json_files else None  
    
def run_processing(directory):
    pdb_files = glob.glob(os.path.join(directory, "*_esm*.pdb"))
    print(f"Found PDB files: {pdb_files}")  # Debugging line
    
    results = []

    for pdb_file in pdb_files:
        pdb_file_basename = os.path.basename(pdb_file)
        parts = pdb_file_basename.split('_')
        pdb_id = parts[0]
        chains_part = "_".join(parts[1:parts.index("esm")])  

        json_file_name = find_matching_json(pdb_file, directory)
        
        if json_file_name and os.path.exists(json_file_name):
            with open(json_file_name, 'r') as json_file:
                json_data = json.load(json_file)
                pae = json_data.get('pae', None)  
            
            if pae is not None:
                file_id = f"{pdb_id}_{chains_part}"

                result = process_pdb_file(pdb_file, json_file_name, 8, pdb_id, chains_part, pae)  
                print(f"Result for {pdb_file}: {result}")
                results.append(result)
            else:
                print(f"PAE not found in JSON file for {pdb_file}.")
        else:
            print(f"JSON file for {pdb_file} not found.")
    
    # Save results to CSV
    if results:
        df = pd.DataFrame(results)
        csv_file_path = f"{file_id}_{str(method)}_pdockq2_fit.csv"  
        df.to_csv(csv_file_path, index=False)
        print(f"Data saved to {csv_file_path}")
    else:
        print("No results to save.")

In [6]:
# Set directory paths
import pandas as pd
import glob
import os

csv_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/newBM_33.csv"
df = pd.read_csv(csv_path)

complex_list=df["pdb_wchains"].to_list()
preds = ["esm"]
for method in preds:
    os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/"+str(method))
    for i in complex_list:
        fpath = f"/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/{method}/{i}_{method}"
        directory = fpath
        run_processing(directory)   
    
    def combine_csv_files(folder_path, output_file=None):
        csv_files = glob.glob(os.path.join(folder_path, "*_pdockq2_fit.csv"))

        df_list = [pd.read_csv(file) for file in csv_files]
        combined_df = pd.concat(df_list, ignore_index=True)
        if output_file:
            combined_df.to_csv(output_file, index=False)
            print(f"Combined CSV saved to {output_file}")
        return combined_df

    folder_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/"+str(method)  
    output_csv = str(method)+"_pdockq2_fit.csv"  
    combined_df = combine_csv_files(folder_path, output_csv)

Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7r58_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7r58_H_L_A_esm/7r58_H_L_A_esm_ptm0.398_r3_default.pdb', 'pdb_id': '7r58', 'Pdb_id_with_chains': '7r58_H_L_A', 'ifpae_norm_ag': 0.13791231170658355, 'ifpae_norm_avg': 0.1292551302979604, 'ifplddt_ag': 75.476, 'ifplddt_avg': 77.03303519668736, 'PdockQ2 Antigen': 0.01007720800710124, 'PdockQ2_avg': 0.009907840237906175}
Data saved to 7r58_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7sjs_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7sjs_H_L_A_esm/7sjs_H_L_A_esm_ptm0.422_r3_default.pdb', 'pdb_id': '7sjs', 'Pdb_id_with_chains': '7sjs_H_L_A', 'ifpae_norm_ag': 0, 'ifpae_norm_avg': 0.0, 'ifplddt_ag': 0, 'ifplddt_avg': 0.0, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.007347788261141952}
Data saved to 7sjs_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7so5_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7so5_H_L_A_esm/7so5_H_L_A_esm_ptm0.570_r3_default.pdb', 'pdb_id': '7so5', 'Pdb_id_with_chains': '7so5_H_L_A', 'ifpae_norm_ag': 0.1171702241448865, 'ifpae_norm_avg': 0.6208169033242498, 'ifplddt_ag': 46.60999999999999, 'ifplddt_avg': 67.84850470957613, 'PdockQ2 Antigen': 0.008518142476748009, 'PdockQ2_avg': 0.2115587309953162}
Data saved to 7so5_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7tp4_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7tp4_H_L_A_esm/7tp4_H_L_A_esm_ptm0.483_r3_default.pdb', 'pdb_id': '7tp4', 'Pdb_id_with_chains': '7tp4_H_L_A', 'ifpae_norm_ag': 0.1225939965674645, 'ifpae_norm_avg': 0.5830511614866426, 'ifplddt_ag': 22.296666666666667, 'ifplddt_avg': 59.75822222222221, 'PdockQ2 Antigen': 0.00787432897165278, 'PdockQ2_avg': 0.15865830287999244}
Data saved to 7tp4_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u2d_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u2d_H_L_A_esm/7u2d_H_L_A_esm_ptm0.420_r3_default.pdb', 'pdb_id': '7u2d', 'Pdb_id_with_chains': '7u2d_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.22835146604582723, 'ifplddt_ag': 0.0, 'ifplddt_avg': 50.108133333333335, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.016482948779538407}
Data saved to 7u2d_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u5b_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7u5b_H_L_A_esm/7u5b_H_L_A_esm_ptm0.578_r3_default.pdb', 'pdb_id': '7u5b', 'Pdb_id_with_chains': '7u5b_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.617805255491222, 'ifplddt_ag': 0.0, 'ifplddt_avg': 55.98513888888889, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.3327057612880094}
Data saved to 7u5b_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uvf_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uvf_H_L_A_esm/7uvf_H_L_A_esm_ptm0.522_r3_default.pdb', 'pdb_id': '7uvf', 'Pdb_id_with_chains': '7uvf_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.38850241838492194, 'ifplddt_ag': 0.0, 'ifplddt_avg': 55.07138888888888, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.059070839172957294}
Data saved to 7uvf_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz7_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz7_H_L_A_esm/7uz7_H_L_A_esm_ptm0.272_r3_default.pdb', 'pdb_id': '7uz7', 'Pdb_id_with_chains': '7uz7_H_L_A', 'ifpae_norm_ag': 0.10715383781971617, 'ifpae_norm_avg': 0.5293009397228531, 'ifplddt_ag': 18.5892, 'ifplddt_avg': 54.661716239316235, 'PdockQ2 Antigen': 0.007720744260660958, 'PdockQ2_avg': 0.12516654018572482}
Data saved to 7uz7_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz8_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7uz8_H_L_A_esm/7uz8_H_L_A_esm_ptm0.278_r3_default.pdb', 'pdb_id': '7uz8', 'Pdb_id_with_chains': '7uz8_H_L_A', 'ifpae_norm_ag': 0.1118975521763529, 'ifpae_norm_avg': 0.5315333191320258, 'ifplddt_ag': 28.955217391304338, 'ifplddt_avg': 59.12345766141319, 'PdockQ2 Antigen': 0.00798422915101845, 'PdockQ2_avg': 0.11962483477669988}
Data saved to 7uz8_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7vaz_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7vaz_H_L_A_esm/7vaz_H_L_A_esm_ptm0.413_r3_default.pdb', 'pdb_id': '7vaz', 'Pdb_id_with_chains': '7vaz_H_L_A', 'ifpae_norm_ag': 0, 'ifpae_norm_avg': 0.0, 'ifplddt_ag': 0, 'ifplddt_avg': 0.0, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.007347788261141952}
Data saved to 7vaz_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7woa_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7woa_H_L_A_esm/7woa_H_L_A_esm_ptm0.272_r3_default.pdb', 'pdb_id': '7woa', 'Pdb_id_with_chains': '7woa_H_L_A', 'ifpae_norm_ag': 0.11199052467682284, 'ifpae_norm_avg': 0.49793044885199117, 'ifplddt_ag': 21.0975, 'ifplddt_avg': 52.81697378951581, 'PdockQ2 Antigen': 0.007796487746414275, 'PdockQ2_avg': 0.05660838442491021}
Data saved to 7woa_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wrl_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wrl_H_L_A_esm/7wrl_H_L_A_esm_ptm0.501_r3_default.pdb', 'pdb_id': '7wrl', 'Pdb_id_with_chains': '7wrl_H_L_A', 'ifpae_norm_ag': 0.1160044326453758, 'ifpae_norm_avg': 0.6364279050152453, 'ifplddt_ag': 22.77, 'ifplddt_avg': 62.614613071895434, 'PdockQ2 Antigen': 0.007854807076665037, 'PdockQ2_avg': 0.2772495800412131}
Data saved to 7wrl_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wsc_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7wsc_H_L_A_esm/7wsc_H_L_A_esm_ptm0.501_r3_default.pdb', 'pdb_id': '7wsc', 'Pdb_id_with_chains': '7wsc_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.568285834968982, 'ifplddt_ag': 0.0, 'ifplddt_avg': 52.477, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.1941537913363421}
Data saved to 7wsc_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7yru_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7yru_H_L_A_esm/7yru_H_L_A_esm_ptm0.604_r3_default.pdb', 'pdb_id': '7yru', 'Pdb_id_with_chains': '7yru_H_L_A', 'ifpae_norm_ag': 0.16274164559877777, 'ifpae_norm_avg': 0.5793404436617419, 'ifplddt_ag': 56.325, 'ifplddt_avg': 72.57595959595959, 'PdockQ2 Antigen': 0.00963028575058858, 'PdockQ2_avg': 0.1572679631175876}
Data saved to 7yru_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7zwi_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/7zwi_H_L_A_esm/7zwi_H_L_A_esm_ptm0.486_r3_default.pdb', 'pdb_id': '7zwi', 'Pdb_id_with_chains': '7zwi_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.30486357743098697, 'ifplddt_ag': 0.0, 'ifplddt_avg': 52.954343434343436, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.028660631874266405}
Data saved to 7zwi_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ath_H_L_A_esm/8ath_H_L_A_esm_ptm0.421_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ath_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ath_H_L_A_esm/8ath_H_L_A_esm_ptm0.421_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ath_H_L_A_esm/8ath_H_L_A_esm_ptm0.421_r3_default.pdb', 'pdb_id': '8ath', 'Pdb_id_with_chains': '8ath_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.19365211266504276, 'ifplddt_ag': 0.0, 'ifplddt_avg': 52.65904761904762, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.014417018067814666}
Data saved to 8ath_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8c3v_H_L_A_esm/8c3v_H_L_A_esm_ptm0.419_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8c3v_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8c3v_H_L_A_esm/8c3v_H_L_A_esm_ptm0.419_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8c3v_H_L_A_esm/8c3v_H_L_A_esm_ptm0.419_r3_default.pdb', 'pdb_id': '8c3v', 'Pdb_id_with_chains': '8c3v_H_L_A', 'ifpae_norm_ag': 0.12560406430520094, 'ifpae_norm_avg': 0.2573791070401769, 'ifplddt_ag': 22.650833333333328, 'ifplddt_avg': 57.1439898989899, 'PdockQ2 Antigen': 0.007898185478076306, 'PdockQ2_avg': 0.01527608876350233}
Data saved to 8c3v_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8cii_H_L_A_esm/8cii_H_L_A_esm_ptm0.485_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8cii_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8cii_H_L_A_esm/8cii_H_L_A_esm_ptm0.485_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8cii_H_L_A_esm/8cii_H_L_A_esm_ptm0.485_r3_default.pdb', 'pdb_id': '8cii', 'Pdb_id_with_chains': '8cii_H_L_A', 'ifpae_norm_ag': 0.13295425964368, 'ifpae_norm_avg': 0.5607387093566805, 'ifplddt_ag': 23.89, 'ifplddt_avg': 61.4573938722776, 'PdockQ2 Antigen': 0.007970172103387336, 'PdockQ2_avg': 0.1432508302413752}
Data saved to 8cii_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d36_H_L_A_esm/8d36_H_L_A_esm_ptm0.597_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d36_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d36_H_L_A_esm/8d36_H_L_A_esm_ptm0.597_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d36_H_L_A_esm/8d36_H_L_A_esm_ptm0.597_r3_default.pdb', 'pdb_id': '8d36', 'Pdb_id_with_chains': '8d36_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.2522026309175907, 'ifplddt_ag': 0.0, 'ifplddt_avg': 52.425061728395065, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.019921530797661926}
Data saved to 8d36_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d9y_H_L_A_esm/8d9y_H_L_A_esm_ptm0.641_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d9y_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d9y_H_L_A_esm/8d9y_H_L_A_esm_ptm0.641_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8d9y_H_L_A_esm/8d9y_H_L_A_esm_ptm0.641_r3_default.pdb', 'pdb_id': '8d9y', 'Pdb_id_with_chains': '8d9y_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.6233553855336186, 'ifplddt_ag': 0.0, 'ifplddt_avg': 56.687152777777776, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.358550301195898}
Data saved to 8d9y_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ds5_H_L_A_esm/8ds5_H_L_A_esm_ptm0.430_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ds5_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ds5_H_L_A_esm/8ds5_H_L_A_esm_ptm0.430_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8ds5_H_L_A_esm/8ds5_H_L_A_esm_ptm0.430_r3_default.pdb', 'pdb_id': '8ds5', 'Pdb_id_with_chains': '8ds5_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.12462577936236191, 'ifplddt_ag': 0.0, 'ifplddt_avg': 54.70019607843138, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.010661531369896534}
Data saved to 8ds5_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8dxt_H_L_A_esm/8dxt_H_L_A_esm_ptm0.444_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8dxt_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8dxt_H_L_A_esm/8dxt_H_L_A_esm_ptm0.444_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8dxt_H_L_A_esm/8dxt_H_L_A_esm_ptm0.444_r3_default.pdb', 'pdb_id': '8dxt', 'Pdb_id_with_chains': '8dxt_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.3255836398388822, 'ifplddt_ag': 0.0, 'ifplddt_avg': 51.197583333333334, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.03108419621565311}
Data saved to 8dxt_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8f6l_H_L_A_esm/8f6l_H_L_A_esm_ptm0.567_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8f6l_H_L_A_esm/converted_pae.json']
Result for /media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8f6l_H_L_A_esm/8f6l_H_L_A_esm_ptm0.567_r3_default.pdb: {'model_id': '/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8f6l_H_L_A_esm/8f6l_H_L_A_esm_ptm0.567_r3_default.pdb', 'pdb_id': '8f6l', 'Pdb_id_with_chains': '8f6l_H_L_A', 'ifpae_norm_ag': 0.0, 'ifpae_norm_avg': 0.5124784528816777, 'ifplddt_ag': 0.0, 'ifplddt_avg': 54.360340136054425, 'PdockQ2 Antigen': 0.007347788261141951, 'PdockQ2_avg': 0.1488307103572542}
Data saved to 8f6l_H_L_A_esm_pdockq2_fit.csv
Found PDB files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8fgx_H_L_A_esm/8fgx_H_L_A_esm_ptm0.464_r3_default.pdb']
Found JSON files: ['/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm/8fgx_H_L_A_esm/converted_pae.json']

In [26]:
import os
import pandas as pd
os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm")  
# !ls *csv
df2 = pd.read_csv('esm_dockq_fnat_scores.csv')
df = pd.read_csv('esm_pdockq2_fit.csv')
df3 = pd.read_csv('esm_metrics_25models.csv')
df2["model_id"] = df2["model_id"].str.replace("_esm_ptm0","")
df["model_id"] =df["Pdb_id_with_chains"]
df4 = pd.merge(df,df2,on="model_id")
# df4
df5 = pd.merge(df4,df3,on="model_id")
df5=df5.drop_duplicates()
df5.to_csv("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/210_recycle20/esm_pdockq2_dockq.csv")
display(df)
display(df2)
display(df3)
df5

,model_id,pdb_id,Pdb_id_with_chains,ifpae_norm_ag,ifpae_norm_avg,ifplddt_ag,ifplddt_avg,PdockQ2 Antigen,PdockQ2_avg
0,7m1h_G_A,7m1h,7m1h_G_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348
1,8d9y_H_L_A,8d9y,8d9y_H_L_A,0.000000,0.623355,0.000000,56.687153,0.007348,0.358550
2,7tcq_H_L_A,7tcq,7tcq_H_L_A,0.000000,0.624447,0.000000,56.916263,0.007348,0.366035
3,7vaz_H_L_A,7vaz,7vaz_H_L_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348
4,8cyj_H_D,8cyj,8cyj_H_D,0.128239,0.129736,25.703333,37.791667,0.007997,0.008405
...,...,...,...,...,...,...,...,...,...
204,7xy8_H_L_A,7xy8,7xy8_H_L_A,0.000000,0.212582,0.000000,56.360631,0.007348,0.017305
205,7l6v_D_A,7l6v,7l6v_D_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348
206,7l6v_F_A,7l6v,7l6v_F_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348
207,8tbq_H_L_A,8tbq,8tbq_H_L_A,0.000000,0.083764,0.000000,50.066667,0.007348,0.008933
208,8eln_H_A,8eln,8eln_H_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348

       model_id     DockQ  fnat      iRMSD       LRMSD   F1
0      8cyj_H_D  0.010013   0.0  17.185648   56.051873  0.0
1      8b17_H_A  0.011878   0.0  23.229414   47.145746  0.0
2      8pyr_H_A  0.005221   0.0  29.755406   73.693801  0.0
3      7nxx_H_A  0.005102   0.0  28.870755   75.206119  0.0
4    7wg3_H_L_A  0.025549   0.0  16.580885   31.337497  0.0
..          ...       ...   ...        ...         ...  ...
204    7voa_H_A  0.014907   0.0  16.774452   43.493251  0.0
205  7ps6_H_L_E  0.005790   0.0  19.080668   79.766587  0.0
206  8hc3_H_L_A  0.001976   0.0  38.225250  127.986431  0.0
207    8emz_H_A  0.012062   0.0  20.171930   47.771999  0.0
208    7l6v_B_A  0.007876   0.0  22.316635   60.862977  0.0

[209 rows x 6 columns]

       model_id    PTM   pLDDT
0    7r58_H_L_A  0.398  77.239
1    7sjs_H_L_A  0.422  73.066
2    7so5_H_L_A  0.570  69.460
3    7tp4_H_L_A  0.483  52.317
4    7u2d_H_L_A  0.420  50.850
..          ...    ...     ...
205  7s11_I_M_D  0.473  72.541
206    7t5f_C_A  0.517  55.668
207    7t5f_E_D  0.558  58.641
208    7vnb_A_B  0.350  43.349
209  7vux_H_L_A  0.526  77.324

[210 rows x 3 columns]

,model_id,pdb_id,Pdb_id_with_chains,ifpae_norm_ag,ifpae_norm_avg,ifplddt_ag,ifplddt_avg,PdockQ2 Antigen,PdockQ2_avg,DockQ,fnat,iRMSD,LRMSD,F1,PTM,pLDDT
0,7m1h_G_A,7m1h,7m1h_G_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,0.019704,0.0,14.955021,37.385247,0.0,0.558,53.819
1,8d9y_H_L_A,8d9y,8d9y_H_L_A,0.000000,0.623355,0.000000,56.687153,0.007348,0.358550,0.007914,0.0,23.838237,59.809277,0.0,0.641,77.071
2,7tcq_H_L_A,7tcq,7tcq_H_L_A,0.000000,0.624447,0.000000,56.916263,0.007348,0.366035,0.004690,0.0,27.329397,80.355779,0.0,0.721,80.437
3,7vaz_H_L_A,7vaz,7vaz_H_L_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,0.009424,0.0,29.855456,52.279414,0.0,0.413,66.695
4,8cyj_H_D,8cyj,8cyj_H_D,0.128239,0.129736,25.703333,37.791667,0.007997,0.008405,0.010013,0.0,17.185648,56.051873,0.0,0.387,46.035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,7xy8_H_L_A,7xy8,7xy8_H_L_A,0.000000,0.212582,0.000000,56.360631,0.007348,0.017305,0.005375,0.0,24.141662,76.237221,0.0,0.488,75.031
205,7l6v_D_A,7l6v,7l6v_D_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,0.023768,0.0,14.859742,33.285885,0.0,0.555,57.979
206,7l6v_F_A,7l6v,7l6v_F_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,0.007812,0.0,22.885468,60.818613,0.0,0.543,57.014
207,8tbq_H_L_A,8tbq,8tbq_H_L_A,0.000000,0.083764,0.000000,50.066667,0.007348,0.008933,0.005759,0.0,21.927116,75.188679,0.0,0.355,67.628
208,8eln_H_A,8eln,8eln_H_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,0.006189,0.0,24.120476,69.551778,0.0,0.667,86.456

In [5]:
import os
import pandas as pd
import re

os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/")

csv_path = "/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/newBM_33.csv"
df = pd.read_csv(csv_path)
complex_list=df["pdb_wchains"].to_list()
x = []

for i in complex_list:
    os.chdir(f"/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm/{i}_esm/")    
    log_file = "output.log" 

    ptm_score = None
    plddt_score = None

    with open(log_file, "r") as f:
        for line in f:
            match = re.search(r"PTM:\s*([\d.]+)\s*pLDDT:\s*([\d.]+)", line)
            if match:
                ptm_score = float(match.group(1))
                plddt_score = float(match.group(2))
                model = i
                break  # Stop after the first match

    df = pd.DataFrame({"model_id":[model],"PTM": [ptm_score], "pLDDT": [plddt_score]})
    x.append(df)
  
os.chdir("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm")

dfx = pd.concat(x, axis=0)
dfx.to_csv("esm_metrics_25models.csv", index=False)
dfx

      model_id    PTM   pLDDT
0   7r58_H_L_A  0.398  77.239
0   7sjs_H_L_A  0.422  73.066
0   7so5_H_L_A  0.570  69.460
0   7tp4_H_L_A  0.483  52.317
0   7u2d_H_L_A  0.420  50.850
..         ...    ...     ...
0   7s11_I_M_D  0.473  72.541
0     7t5f_C_A  0.517  55.668
0     7t5f_E_D  0.558  58.641
0     7vnb_A_B  0.350  43.349
0   7vux_H_L_A  0.526  77.324

[210 rows x 3 columns]

In [6]:
df4 = pd.merge(df3,dfx,on="model_id")
df4.to_csv("/media/emel/WD_3tb/Ab-Ag_benchmark_boltz_chai/paper/esm_pdockq2_dockq_metrics.csv")
df4

,model_id,pdb_id,Pdb_id_with_chains,ifpae_norm_ag,ifpae_norm_avg,ifplddt_ag,ifplddt_avg,PdockQ2 Antigen,PdockQ2_avg,ifpae_norm,...,prot_avg,PdockQ2,1 - Average PAE Interface Antigen,DockQ,fnat,iRMSD,LRMSD,F1,PTM,pLDDT
0,7m1h_G_A,7m1h,7m1h_G_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,NaN,...,NaN,NaN,NaN,0.019704,0.0,14.955021,37.385247,0.0,0.558,53.819
1,8d9y_H_L_A,8d9y,8d9y_H_L_A,0.000000,0.623355,0.000000,56.687153,0.007348,0.358550,NaN,...,NaN,NaN,NaN,0.007914,0.0,23.838237,59.809277,0.0,0.641,77.071
2,7tcq_H_L_A,7tcq,7tcq_H_L_A,0.000000,0.624447,0.000000,56.916263,0.007348,0.366035,NaN,...,NaN,NaN,NaN,0.004690,0.0,27.329397,80.355779,0.0,0.721,80.437
3,7vaz_H_L_A,7vaz,7vaz_H_L_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,NaN,...,NaN,NaN,NaN,0.009424,0.0,29.855456,52.279414,0.0,0.413,66.695
4,8cyj_H_D,8cyj,8cyj_H_D,0.128239,0.129736,25.703333,37.791667,0.007997,0.008405,NaN,...,NaN,NaN,NaN,0.010013,0.0,17.185648,56.051873,0.0,0.387,46.035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,7xy8_H_L_A,7xy8,7xy8_H_L_A,0.000000,0.212582,0.000000,56.360631,0.007348,0.017305,NaN,...,NaN,NaN,NaN,0.005375,0.0,24.141662,76.237221,0.0,0.488,75.031
414,7l6v_D_A,7l6v,7l6v_D_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,NaN,...,NaN,NaN,NaN,0.023768,0.0,14.859742,33.285885,0.0,0.555,57.979
415,7l6v_F_A,7l6v,7l6v_F_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,NaN,...,NaN,NaN,NaN,0.007812,0.0,22.885468,60.818613,0.0,0.543,57.014
416,8tbq_H_L_A,8tbq,8tbq_H_L_A,0.000000,0.083764,0.000000,50.066667,0.007348,0.008933,NaN,...,NaN,NaN,NaN,0.005759,0.0,21.927116,75.188679,0.0,0.355,67.628
417,8eln_H_A,8eln,8eln_H_A,0.000000,0.000000,0.000000,0.000000,0.007348,0.007348,NaN,...,NaN,NaN,NaN,0.006189,0.0,24.120476,69.551778,0.0,0.667,86.456